# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_s', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizz',
            new_name='Pizza',
        ),
    ]
