"""initial migration

Revision ID: 441ead6b202d
Revises: d1add127e588
Create Date: 2017-09-21 15:41:19.038947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441ead6b202d'
down_revision = 'd1add127e588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
