"""initial migration

Revision ID: 543c65b37c08
Revises: 4b49aed5aa65
Create Date: 2017-09-14 16:18:47.901607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543c65b37c08'
down_revision = '4b49aed5aa65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
